- name: d2_ele1
  approach:
    - from: f2_ele1
      point: [24.55, 29.75, 4.71239]
    - from: f2_corr1,f2_main,f2_corr2,f2_corr3,f2_side,f2_drink,f2_coffee,f2_main_plus
      point: [24.45, 32.55, 4.74809]
- name: d2_ele2
  approach:
    - from: f2_corr1,f2_main,f2_corr2,f2_corr3,f2_side,f2_drink,f2_coffee,f2_main_plus
      point: [27.4, 32.1, -1.46592]
    - from: f2_ele2
      point: [27.6, 30.2, 1.67567]
