- name: d3_414a3
  approach:
    - from: l3_414b
      point: [13.9, 13.75, 3.14159]
    - from: l3_414b1
      point: [12.4, 13.75, 6.28319]
- name: d3_414b3
  approach:
    - from: l3_414b2
      point: [18.8, 13.75, 3.14159]
    - from: l3_414b
      point: [17.4, 13.75, 6.28319]
- name: d3_414a2
  approach:
    - from: l3_414b1
      point: [6.45, 9.75, -1.50838]
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [6.55, 8.15, 1.63322]
- name: d3_414a1
  approach:
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [6.65, 15.35, -1.51821]
    - from: l3_414b1
      point: [6.75, 13.45, 1.62338]
- name: d3_414b2
  approach:
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [24.7, 14.95, -1.63737]
    - from: l3_414b2
      point: [24.6, 13.45, 1.50423]
- name: d3_414b1
  approach:
    - from: l3_414b2
      point: [24.25, 9.7, -1.46014]
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [24.45, 7.9, 1.68145]
- name: d3_5161
  approach:
    - from: l3_516
      point: [20.05, 4.7, 3.14159]
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [18.45, 4.7, 6.28319]
- name: d3_5162
  approach:
    - from: l3_400,l3_406,l3_408,l3_410,l3_424,l3_500,l3_504,l3_506,l3_514,l3_518,l3_520
      point: [26.05, 7.8, -1.5708]
    - from: l3_516
      point: [26.05, 6.2, 1.5708]
