- name: d3_502
  approach:
    - from: cor
      point: [-4.3, 8.15, -1.5708]
    - from: o3_502
      point: [-4.3, 6.35, 1.24905]
  width: 0.9
- name: d3_508
  approach:
    - from: cor
      point: [7.2, 8.15, -1.5708]
    - from: o3_508
      point: [7.2, 6.35, 1.30455]
  width: 0.9
- name: d3_510
  approach:
    - from: cor
      point: [8.4, 8.15, -1.48014]
    - from: o3_510
      point: [8.4, 6.35, 1.69515]
  width: 0.9
- name: d3_512
  approach:
    - from: cor
      point: [14.9, 8.15, -1.67047]
    - from: o3_512
      point: [14.9, 6.35, 1.42191]
  width: 0.9
# - name: d3_5161
#   approach:
#     - from: s3_516
#       point: [20.25, 4.8, 3.14159]
#     - from: cor
#       point: [18.45, 4.8, 0]
#   width: 2.0
# - name: d3_5162
#   approach:
#     - from: cor
#       point: [26.35, 8.15, -1.81578]
#     - from: s3_516
#       point: [26.35, 6.35, 1.52915]
#   width: 0.9
# - name: d3_4361
#   approach:
#     - from: l3_436
#       point: [37.8, 8.35, 3.06482]
#     - from: cor
#       point: [36.25, 8.35, 0]
#   width: 0.9
# - name: d3_4362
#   approach:
#     - from: l3_436
#       point: [35.6, 15.45, 3.14159]
#     - from: cor
#       point: [33.7, 15.45, -0.124356]
#   width: 0.9
- name: d3_428
  approach:
    - from: cor
      point: [28.85, 15.3, -1.5708]
    - from: o3_428
      point: [28.85, 13.7, 1.7976]
  width: 0.9
- name: d3_426
  approach:
    - from: o3_426
      point: [26.05, 13.7, 1.67046]
    - from: cor
      point: [26.05, 15.3, -1.46014]
  width: 0.9
# - name: d3_414b1
#   approach:
#     - from: cor
#       point: [24.9, 15.3, -1.5708]
#     - from: l3_414b
#       point: [24.9, 13.7, 1.50423]
#   width: 0.9
# - name: d3_414b2
#   approach:
#     - from: cor
#       point: [24.4, 8.1, 1.5708]
#     - from: l3_414b
#       point: [24.4, 9.8, -1.5708]
#   width: 1.8
# - name: d3_414b3
#   approach:
#     - from: l3_414b
#       point: [18.85, 13.9, 3.14159]
#     - from: l3_414
#       point: [17.25, 13.9, 0]
#   width: 0.9
# - name: d3_414a3
#   approach:
#     - from: l3_414
#       point: [13.45, 13.9, 3.14159]
#     - from: l3_414a
#       point: [11.85, 13.9, 0]
#   width: 0.9
# - name: d3_414a2
#   approach:
#     - from: l3_414a
#       point: [6.05, 9.8, -1.5708]
#     - from: cor
#       point: [6.05, 8.1, 1.31347]
#   width: 0.9
# - name: d3_414a1
#   approach:
#     - from: cor
#       point: [6.6, 15.3, -1.47113]
#     - from: l3_414a
#       point: [6.6, 13.7, 1.5708]
#   width: 1.8
# - name: d3_412
#   approach:
#     - from: cor
#       point: [4.9, 15.3, -1.64757]
#     - from: o3_412
#       point: [4.9, 13.7, 1.48013]
#   width: 0.9
# - name: d3_402
#   approach:
#     - from: cor
#       point: [-8.2, 15.2, 1.5708]
#     - from: o3_402
#       point: [-8.2, 17.2, -1.32582]
#   width: 0.9
# - name: d3_404
#   approach:
#     - from: o3_404
#       point: [-7.05, 17.2, -1.72345]
#     - from: cor
#       point: [-7.05, 15.2, 1.47113]
#   width: 0.9
# - name: d3_416
#   approach:
#     - from: o3_416
#       point: [7.2, 17.2, -1.47113]
#     - from: cor
#       point: [7.2, 15.2, 1.68145]
#   width: 0.9
# - name: d3_418
#   approach:
#     - from: o3_418
#       point: [8.35, 17.2, -1.97569]
#     - from: cor
#       point: [8.35, 15.2, 1.5708]
#   width: 0.9
# - name: d3_420
#   approach:
#     - from: o3_420
#       point: [14.9, 17.2, -1.50423]
#     - from: cor
#       point: [14.9, 15.2, 1.5708]
#   width: 0.9
# - name: d3_422
#   approach:
#     - from: o3_422
#       point: [16.05, 17.2, -1.97569]
#     - from: cor
#       point: [16.05, 15.2, 1.48014]
#   width: 0.9
# - name: d3_430
#   approach:
#     - from: o3_430
#       point: [30.2, 17.2, -1.49403]
#     - from: cor
#       point: [30.2, 15.2, 1.48765]
#   width: 0.9
# - name: d3_432
#   approach:
#     - from: o3_432
#       point: [31.4, 17.2, -1.98902]
#     - from: cor
#       point: [31.4, 15.2, 1.5708]
#   width: 0.9
